openapi: 3.0.0
info:
  title: Authentication
  version: 0.0.0
tags: []
paths:
  /api/auth/sign-in:
    post:
      operationId: signIn
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthCredentials'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiDocs.Api.BadRequestError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiDocs.Api.UnexpectedError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInCredentials'
  /api/auth/sign-up:
    post:
      operationId: signUp
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WelcomeMessage'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiDocs.Api.BadRequestError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiDocs.Api.UnexpectedError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpCredentials'
components:
  schemas:
    ApiDocs.Api.BadRequestError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          enum:
            - Invalid data
    ApiDocs.Api.UnexpectedError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          enum:
            - An unexpected error occurred
    AuthCredentials:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          enum:
            - 745731af4484f323968969eda289aeee
      description: Authentication token
    SignInCredentials:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    SignUpCredentials:
      type: object
      required:
        - first_name
        - last_name
        - email
        - password
        - role
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
          enum:
            - patient
            - doctor
    WelcomeMessage:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          enum:
            - Please check your email address for a verification code
