name: docs-staging

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout current repo state
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create output folder
        run: mkdir __site

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Build internal docs
        working-directory: docs/docs
        run: |
          nix build .#packages.x86_64-linux.docs
          mkdir -p ../../__site/docs/docs
          cp -r result/* ../../__site/docs/docs

      - name: Check built internal docs
        working-directory: docs/docs
        run: nix flake check

      - name: Install dependencies
        working-directory: packages
        run: pnpm install

      - name: Setup assets
        working-directory: packages
        run: |
          pnpm compile
          pnpm typegen

      - name: Build api docs
        working-directory: packages/@beta-lyfe/docs-api
        run: |
          pnpm build --base /api
          mkdir -p ../../../__site/docs/api
          cp -r dist/* ../../../__site/docs/api

      - name: Deploy docs
        working-directory: __site
        run: |
          mkdir -p .vercel/output/static
          echo '{ "version": 3 }' > .vercel/output/config.json
          mv docs/* .vercel/output/static
          nix run nixpkgs#bun -- x vercel deploy --prebuilt --target staging --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_API_DOCS_PROJECT_ID }}
