name: production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout current repo state
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create output folder
        run: mkdir __site

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Install dependencies
        working-directory: packages
        run: pnpm install

      - name: Setup assets
        working-directory: packages
        run: |
          pnpm compile
          pnpm typegen

      - name: Load .env file
        working-directory: packages
        run: |
          DOCS_ENV_FILE="$(mktemp)"
          WEBAPP_ENV_FILE="$(mktemp)"
          WEBSITE_ENV_FILE="$(mktemp)"
          BACKEND_ENV_FILE="$(mktemp)"

          VERCEL_ENVIRONMENT="production"

          export VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}
          export VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}

          export VERCEL_PROJECT_ID=${{ secrets.VERCEL_DOCS_PROJECT_ID }}
          pnpm vercel env pull "$DOCS_ENV_FILE" --yes --environment "$VERCEL_ENVIRONMENT" --token "$VERCEL_TOKEN"

          export VERCEL_PROJECT_ID=${{ secrets.VERCEL_WEBAPP_PROJECT_ID }}
          pnpm vercel env pull "$WEBAPP_ENV_FILE" --yes --environment "$VERCEL_ENVIRONMENT" --token "$VERCEL_TOKEN"

          export VERCEL_PROJECT_ID=${{ secrets.VERCEL_WEBSITE_PROJECT_ID }}
          pnpm vercel env pull "$WEBSITE_ENV_FILE" --yes --environment "$VERCEL_ENVIRONMENT"  --token "$VERCEL_TOKEN"

          export VERCEL_PROJECT_ID=${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
          pnpm vercel env pull "$BACKEND_ENV_FILE" --yes --environment "$VERCEL_ENVIRONMENT"  --token "$VERCEL_TOKEN"

          cat "$DOCS_ENV_FILE" >> .env
          cat "$WEBAPP_ENV_FILE" >> .env
          cat "$WEBSITE_ENV_FILE" >> .env
          cat "$BACKEND_ENV_FILE" >> .env
          echo VERCEL_TOKEN="$VERCEL_TOKEN" >> .env
          echo VERCEL_ENVIRONMENT="$VERCEL_ENVIRONMENT" >> .env

          cat .env | grep -v '^#' | sed -E 's/^(.*)?="(.*)"/\1=\2/' >> "$GITHUB_ENV"

      - name: Build internal docs
        working-directory: docs/docs
        run: |
          nix build .#packages.x86_64-linux.docs
          mkdir -p ../../__site/docs/docs
          cp -r result/* ../../__site/docs/docs

      - name: Check built internal docs
        working-directory: docs/docs
        run: nix flake check

      - name: Build stack
        working-directory: packages
        run: pnpm build

      - name: Move api docs to output folder
        working-directory: packages/@beta-lyfe/docs-api
        run: |
          mkdir -p ../../../__site/docs/api
          cp -r dist/* ../../../__site/docs/api

      - name: Deploy docs
        working-directory: __site
        run: |
          mkdir -p .vercel/output/static
          echo '{ "version": 3 }' > .vercel/output/config.json
          mv docs/* .vercel/output/static
          nix run nixpkgs#bun -- x vercel deploy --prebuilt --target "$VERCEL_ENVIRONMENT" --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_PROJECT_ID }}

      - name: Deploy website
        working-directory: packages
        run: pnpm --filter @beta-lyfe/website run deploy --target "$VERCEL_ENVIRONMENT" 
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEBSITE_PROJECT_ID }}

      - name: Deploy webapp
        working-directory: packages
        run: pnpm --filter @beta-lyfe/webapp run deploy --target "$VERCEL_ENVIRONMENT"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEBAPP_PROJECT_ID }}

      - name: Deploy backend
        working-directory: packages
        run: pnpm --filter @beta-lyfe/standup-backend run deploy --target "$VERCEL_ENVIRONMENT"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}

